/**
 * Deep-Check INTEL — Local JWT Authentication
 *
 * Used when DEPLOY_MODE=intel or OFFLINE_MODE=true.
 * No Supabase Auth, no magic links, no phone-home.
 *
 * Authentication flow:
 *   1. Client POSTs username + password to /api/auth/local-login
 *   2. Server validates against LOCAL_USERS env var (JSON array) or users.json
 *   3. Server issues a signed JWT (HS256, manual implementation — no jsonwebtoken dep)
 *   4. Client stores JWT in dc_local_token cookie or Authorization header
 *
 * JWT is implemented manually with Node.js crypto (HMAC-SHA256).
 * jsonwebtoken is NOT a dependency of this project.
 */

import { createHmac, timingSafeEqual } from 'crypto'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface LocalUser {
  id: string
  username: string
  role: 'admin' | 'analyst' | 'viewer'
  orgId: string
  createdAt: string
}

export interface AuthResult {
  success: boolean
  token?: string      // Signed JWT
  user?: LocalUser
  error?: string
}

// Internal stored user record (includes password_hash)
interface StoredUser {
  id?: string
  username: string
  password_hash: string
  role: 'admin' | 'analyst' | 'viewer'
  orgId?: string
  org_id?: string     // alternative casing used in SQL-sourced records
  createdAt?: string
  created_at?: string
}

// JWT payload
interface JwtPayload {
  sub: string         // user id
  username: string
  role: 'admin' | 'analyst' | 'viewer'
  orgId: string
  iat: number         // issued at (seconds)
  exp: number         // expires at (seconds)
}

// ─── Configuration ────────────────────────────────────────────────────────────

const JWT_EXPIRY_SECONDS = 60 * 60 * 8   // 8 hours
const COOKIE_NAME = 'dc_local_token'

// ─── Manual JWT (HS256) ───────────────────────────────────────────────────────

function base64UrlEncode(data: string | Buffer): string {
  const b64 = Buffer.isBuffer(data)
    ? data.toString('base64')
    : Buffer.from(data).toString('base64')
  return b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '')
}

function base64UrlDecode(input: string): string {
  const padded = input
    .replace(/-/g, '+')
    .replace(/_/g, '/')
    .padEnd(input.length + (4 - (input.length % 4)) % 4, '=')
  return Buffer.from(padded, 'base64').toString('utf8')
}

function jwtSign(payload: JwtPayload, secret: string): string {
  const header = base64UrlEncode(JSON.stringify({ alg: 'HS256', typ: 'JWT' }))
  const body = base64UrlEncode(JSON.stringify(payload))
  const sigInput = `${header}.${body}`
  const signature = createHmac('sha256', secret)
    .update(sigInput)
    .digest()
  return `${sigInput}.${base64UrlEncode(signature)}`
}

function jwtVerify(
  token: string,
  secret: string
): { valid: boolean; payload?: JwtPayload; error?: string } {
  const parts = token.split('.')
  if (parts.length !== 3) {
    return { valid: false, error: 'Malformed JWT: expected 3 parts.' }
  }

  const [headerB64, bodyB64, sigB64] = parts
  const sigInput = `${headerB64}.${bodyB64}`

  // Recompute expected signature
  const expectedSigBuf = createHmac('sha256', secret)
    .update(sigInput)
    .digest()
  const expectedSigB64 = base64UrlEncode(expectedSigBuf)

  // Constant-time comparison
  const expectedBuf = Buffer.from(expectedSigB64, 'utf8')
  const actualBuf = Buffer.from(sigB64, 'utf8')

  if (
    expectedBuf.length !== actualBuf.length ||
    !timingSafeEqual(expectedBuf, actualBuf)
  ) {
    return { valid: false, error: 'JWT signature invalid.' }
  }

  let payload: JwtPayload
  try {
    payload = JSON.parse(base64UrlDecode(bodyB64)) as JwtPayload
  } catch {
    return { valid: false, error: 'JWT payload could not be decoded.' }
  }

  const now = Math.floor(Date.now() / 1000)
  if (payload.exp && payload.exp < now) {
    return { valid: false, error: 'JWT has expired.' }
  }

  return { valid: true, payload }
}

// ─── Password hashing (bcrypt-free, PBKDF2) ───────────────────────────────────

/**
 * Hash a password using PBKDF2-SHA256.
 * Format: pbkdf2$<iterations>$<salt_hex>$<hash_hex>
 *
 * This is used when creating users programmatically. For passwords pre-hashed
 * with bcrypt (from external tools), see verifyPassword below.
 */
export async function hashPassword(password: string): Promise<string> {
  const { pbkdf2, randomBytes } = await import('crypto')
  const salt = randomBytes(32)
  return new Promise((resolve, reject) => {
    pbkdf2(password, salt, 210_000, 64, 'sha256', (err, derivedKey) => {
      if (err) reject(err)
      else resolve(`pbkdf2$210000$${salt.toString('hex')}$${derivedKey.toString('hex')}`)
    })
  })
}

/**
 * Verify a password against a stored hash.
 * Supports:
 *   - pbkdf2$<iterations>$<salt>$<hash>  (generated by hashPassword)
 *   - Plain text (for initial setup / testing only — NOT recommended)
 *
 * bcrypt hashes ($2b$...) are detected and rejected with a clear error
 * since this project does not install bcrypt.
 */
async function verifyPassword(password: string, storedHash: string): Promise<boolean> {
  if (storedHash.startsWith('pbkdf2$')) {
    const parts = storedHash.split('$')
    if (parts.length !== 4) return false
    const [, iterStr, saltHex, hashHex] = parts
    const iterations = parseInt(iterStr, 10)
    const salt = Buffer.from(saltHex, 'hex')
    const expectedHash = Buffer.from(hashHex, 'hex')

    const { pbkdf2 } = await import('crypto')
    return new Promise((resolve, reject) => {
      pbkdf2(password, salt, iterations, expectedHash.length, 'sha256', (err, derivedKey) => {
        if (err) { reject(err); return }
        resolve(
          derivedKey.length === expectedHash.length &&
          timingSafeEqual(derivedKey, expectedHash)
        )
      })
    })
  }

  if (storedHash.startsWith('$2b$') || storedHash.startsWith('$2a$')) {
    // bcrypt detected — this project does not have bcrypt installed.
    // Convert hashes to pbkdf2 format with the generate-users script.
    console.error(
      '[localAuth] bcrypt hash detected. Install bcrypt or re-hash with scripts/generate-users.js'
    )
    return false
  }

  // Fallback: plain-text comparison (dev/setup only — always log a warning)
  console.warn('[localAuth] WARNING: plain-text password comparison used. Hash passwords in production.')
  const a = Buffer.from(password, 'utf8')
  const b = Buffer.from(storedHash, 'utf8')
  if (a.length !== b.length) return false
  return timingSafeEqual(a, b)
}

// ─── User store ───────────────────────────────────────────────────────────────

/**
 * Load the list of local users from:
 *   1. LOCAL_USERS environment variable (JSON array)
 *   2. ./users.json or /app/license/users.json on disk
 *
 * Returns an empty array if neither source is available.
 */
function loadStoredUsers(): StoredUser[] {
  // 1. Environment variable
  const envUsers = process.env.LOCAL_USERS
  if (envUsers && envUsers.trim().startsWith('[')) {
    try {
      return JSON.parse(envUsers) as StoredUser[]
    } catch {
      console.error('[localAuth] Failed to parse LOCAL_USERS env var as JSON array.')
    }
  }

  // 2. File on disk
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require('fs') as typeof import('fs')
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require('path') as typeof import('path')

    const candidates = [
      path.join(process.cwd(), 'license', 'users.json'),
      '/app/license/users.json',
      path.join(process.cwd(), 'users.json'),
    ]

    for (const candidate of candidates) {
      if (fs.existsSync(candidate)) {
        const content = fs.readFileSync(candidate, 'utf8')
        return JSON.parse(content) as StoredUser[]
      }
    }
  } catch {
    // fs not available or file missing — fall through
  }

  return []
}

/**
 * Resolve orgId from a stored user record (handles both camelCase and snake_case).
 */
function resolveOrgId(user: StoredUser): string {
  return user.orgId || user.org_id || 'local'
}

/**
 * Resolve user id from a stored user record (generates one if missing).
 */
function resolveUserId(user: StoredUser): string {
  return user.id || `local-${user.username}`
}

/**
 * Resolve createdAt from a stored user record.
 */
function resolveCreatedAt(user: StoredUser): string {
  return user.createdAt || user.created_at || new Date(0).toISOString()
}

// ─── JWT secret ───────────────────────────────────────────────────────────────

function getJwtSecret(): string {
  const secret = process.env.LOCAL_JWT_SECRET
  if (!secret || secret.trim().length < 32) {
    throw new Error(
      'LOCAL_JWT_SECRET must be set and at least 32 characters long.'
    )
  }
  return secret
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Authenticate with username + password.
 *
 * Checks against LOCAL_USERS env var (JSON array) or local users.json file.
 * Returns a signed JWT on success.
 */
export async function localLogin(username: string, password: string): Promise<AuthResult> {
  if (!username || !password) {
    return { success: false, error: 'Username and password are required.' }
  }

  let secret: string
  try {
    secret = getJwtSecret()
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'JWT secret not configured.',
    }
  }

  const users = loadStoredUsers()
  if (users.length === 0) {
    return {
      success: false,
      error:
        'No local users configured. Set LOCAL_USERS env var or provide /app/license/users.json.',
    }
  }

  const storedUser = users.find(
    (u) => u.username.toLowerCase() === username.toLowerCase()
  )
  if (!storedUser) {
    // Use a fixed-time response to prevent username enumeration
    await verifyPassword(password, 'pbkdf2$210000$dummy$dummy')
    return { success: false, error: 'Invalid credentials.' }
  }

  const passwordOk = await verifyPassword(password, storedUser.password_hash)
  if (!passwordOk) {
    return { success: false, error: 'Invalid credentials.' }
  }

  const user: LocalUser = {
    id: resolveUserId(storedUser),
    username: storedUser.username,
    role: storedUser.role,
    orgId: resolveOrgId(storedUser),
    createdAt: resolveCreatedAt(storedUser),
  }

  const now = Math.floor(Date.now() / 1000)
  const payload: JwtPayload = {
    sub: user.id,
    username: user.username,
    role: user.role,
    orgId: user.orgId,
    iat: now,
    exp: now + JWT_EXPIRY_SECONDS,
  }

  const token = jwtSign(payload, secret)

  return { success: true, token, user }
}

/**
 * Verify a JWT token previously issued by localLogin.
 *
 * Returns { valid: true, user } on success or { valid: false } on failure.
 * Does not throw.
 */
export function verifyLocalToken(token: string): { valid: boolean; user?: LocalUser } {
  if (!token) return { valid: false }

  let secret: string
  try {
    secret = getJwtSecret()
  } catch {
    return { valid: false }
  }

  const result = jwtVerify(token, secret)
  if (!result.valid || !result.payload) return { valid: false }

  const { payload } = result
  const user: LocalUser = {
    id: payload.sub,
    username: payload.username,
    role: payload.role,
    orgId: payload.orgId,
    createdAt: new Date(payload.iat * 1000).toISOString(),
  }

  return { valid: true, user }
}

/**
 * Middleware helper: extract and verify a JWT from the Authorization header
 * or the dc_local_token cookie.
 *
 * Usage in a Next.js API route:
 *   const user = await getLocalUser(req)
 *   if (!user) return res.status(401).json({ error: 'Unauthorized' })
 *
 * Accepts standard Web Request (Next.js App Router) or Node.js IncomingMessage.
 */
export async function getLocalUser(req: Request): Promise<LocalUser | null> {
  // 1. Authorization: Bearer <token>
  const authHeader = req.headers.get('authorization')
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.slice(7).trim()
    const { valid, user } = verifyLocalToken(token)
    if (valid && user) return user
  }

  // 2. Cookie: dc_local_token=<token>
  const cookieHeader = req.headers.get('cookie')
  if (cookieHeader) {
    const cookies = Object.fromEntries(
      cookieHeader.split(';').map((c) => {
        const [k, ...v] = c.trim().split('=')
        return [k.trim(), v.join('=')]
      })
    )
    const cookieToken = cookies[COOKIE_NAME]
    if (cookieToken) {
      const { valid, user } = verifyLocalToken(cookieToken)
      if (valid && user) return user
    }
  }

  return null
}

/**
 * Returns true when the application is running in offline / Intel mode.
 *
 * Checks OFFLINE_MODE and DEPLOY_MODE environment variables.
 * Safe to call on both server and client (NEXT_PUBLIC_ prefix not needed
 * because this file is server-only).
 */
export function isOfflineMode(): boolean {
  return (
    process.env.OFFLINE_MODE === 'true' ||
    process.env.DEPLOY_MODE === 'intel'
  )
}
