/**
 * pdfToImage.ts — Server-side PDF → image converter
 * ===================================================
 * Extracts raster images from PDF files using multiple strategies:
 *
 * Strategy 1: pdfjs-dist canvas render (works for digital/text PDFs)
 * Strategy 2: Raw JPEG extraction (works for scanned documents)
 *             Scanned PDFs embed a JPEG image stream directly.
 *             We find the JPEG by looking for FFD8FF magic bytes.
 *
 * Works for all PDF types:
 *   - Scanned documents (image-only PDFs: DNI, passport, degree scans)
 *   - Digital / text PDFs (CVs, transcripts generated by Word/LaTeX)
 *   - Multi-page PDFs (only page 1 / first image is processed)
 *
 * Graceful degradation: returns null on any failure so callers can
 * fall back to OCR-only mode.
 */

import path from 'path'

// Scale factor: 200 DPI (72 is PDF native DPI → ×2.78 ≈ 200 DPI)
const RENDER_SCALE = 2.78

// pdfjs worker path (resolved at module load time)
const WORKER_PATH = path.resolve(
  process.cwd(),
  'node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs',
)

// JPEG magic bytes
const JPEG_SOI = Buffer.from([0xFF, 0xD8, 0xFF])
const JPEG_EOI = Buffer.from([0xFF, 0xD9])

/**
 * Extract an embedded JPEG from a scanned PDF.
 * Scanned documents are PDFs that wrap a single JPEG/PNG image.
 * The JPEG is found by searching for FFD8FF..FFD9 in the raw bytes.
 *
 * @param pdfBuffer  Raw PDF bytes
 * @returns          JPEG data URL, or null if no JPEG found
 */
function extractJpegFromPdf(pdfBuffer: Buffer): string | null {
  const jpegStart = pdfBuffer.indexOf(JPEG_SOI)
  if (jpegStart < 0) return null

  const jpegEnd = pdfBuffer.indexOf(JPEG_EOI, jpegStart)
  if (jpegEnd < 0) return null

  const jpegData = pdfBuffer.subarray(jpegStart, jpegEnd + 2)

  // Sanity check: JPEG should be at least 10KB for a document scan
  if (jpegData.length < 10_000) return null

  const b64 = jpegData.toString('base64')
  return `data:image/jpeg;base64,${b64}`
}

/**
 * Convert the first page of a PDF (base64 data URL or raw base64) to an image.
 *
 * Tries two strategies:
 *   1. pdfjs-dist canvas render (for text/vector PDFs)
 *   2. Raw JPEG extraction (for scanned document PDFs)
 *
 * @param pdfInput  data URL ("data:application/pdf;base64,...") or raw base64
 * @returns         Image data URL (PNG or JPEG), or null on failure
 */
export async function pdfFirstPageToPng(pdfInput: string): Promise<string | null> {
  const b64 = pdfInput.includes(',') ? pdfInput.split(',')[1] : pdfInput
  const pdfBuffer = Buffer.from(b64, 'base64')

  // ── Strategy 1: pdfjs-dist canvas render ──────────────────────────────────
  try {
    const { getDocument, GlobalWorkerOptions } = await import(
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore — pdfjs-dist v4 is ESM-only; no CJS types available
      'pdfjs-dist/legacy/build/pdf.mjs'
    ) as typeof import('pdfjs-dist')

    GlobalWorkerOptions.workerSrc = WORKER_PATH

    const loadingTask = getDocument({
      data:            new Uint8Array(pdfBuffer),
      verbosity:       0,
      disableFontFace: true,
      isEvalSupported: false,
    })
    const pdf = await loadingTask.promise
    const page     = await pdf.getPage(1)
    const viewport = page.getViewport({ scale: RENDER_SCALE })
    const width    = Math.round(viewport.width)
    const height   = Math.round(viewport.height)

    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { createCanvas } = require('canvas') as typeof import('canvas')
    const canvas  = createCanvas(width, height)
    const ctx     = canvas.getContext('2d')

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (page.render as any)({ canvasContext: ctx, viewport }).promise
    await pdf.destroy()

    console.log('[pdfToImage] pdfjs-dist render succeeded')
    return canvas.toDataURL('image/png')
  } catch (err) {
    console.warn('[pdfToImage] pdfjs-dist render failed, trying JPEG extraction:', err instanceof Error ? err.message : err)
  }

  // ── Strategy 2: Extract embedded JPEG from scanned PDF ────────────────────
  try {
    const jpeg = extractJpegFromPdf(pdfBuffer)
    if (jpeg) {
      console.log('[pdfToImage] Embedded JPEG extracted successfully')
      return jpeg
    }
    console.warn('[pdfToImage] No embedded JPEG found in PDF')
  } catch (err) {
    console.warn('[pdfToImage] JPEG extraction failed:', err instanceof Error ? err.message : err)
  }

  return null
}

/**
 * Quick check: is this input likely a PDF?
 */
export function isPdfInput(input: string): boolean {
  if (input.startsWith('data:application/pdf'))   return true
  if (input.startsWith('data:application/x-pdf')) return true
  // Check raw base64 magic bytes: %PDF = 0x25 0x50 0x44 0x46 → base64 "JVBE"
  const raw = input.includes(',') ? input.split(',')[1] : input
  return raw.startsWith('JVBE')
}
