/**
 * pdfToImage.ts — Server-side PDF → PNG converter
 * =================================================
 * Renders the first page of a PDF to a PNG data URL using
 * pdfjs-dist (legacy ESM build) + node-canvas.
 *
 * Works for all PDF types:
 *   • Scanned documents (image-only PDFs: DNI, passport, degree scans)
 *   • Digital / text PDFs (CVs, transcripts generated by Word/LaTeX)
 *   • Multi-page PDFs (only page 1 is rendered)
 *
 * Output resolution: 200 DPI equivalent (scale = 200/72 ≈ 2.78×)
 * Output format: PNG data URL suitable for Sharp / CNN / Rekognition
 *
 * Graceful degradation: returns null on any failure so callers can
 * fall back to Textract-only mode.
 */

import path from 'path'

// Scale factor: 200 DPI (72 is PDF native DPI → ×2.78 ≈ 200 DPI)
const RENDER_SCALE = 2.78

// pdfjs worker path (resolved at module load time)
const WORKER_PATH = path.resolve(
  process.cwd(),
  'node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs',
)

/**
 * Convert the first page of a PDF (base64 data URL or raw base64) to PNG.
 *
 * @param pdfInput  data URL ("data:application/pdf;base64,...") or raw base64
 * @returns         PNG data URL, or null on failure
 */
export async function pdfFirstPageToPng(pdfInput: string): Promise<string | null> {
  try {
    // ── Extract raw base64 ───────────────────────────────────────────────────
    const b64 = pdfInput.includes(',') ? pdfInput.split(',')[1] : pdfInput
    const pdfBuffer = Buffer.from(b64, 'base64')

    // ── Load pdfjs dynamically (ESM, lazy) ───────────────────────────────────
    const { getDocument, GlobalWorkerOptions } = await import(
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore — pdfjs-dist v4 is ESM-only; no CJS types available
      'pdfjs-dist/legacy/build/pdf.mjs'
    ) as typeof import('pdfjs-dist')

    GlobalWorkerOptions.workerSrc = WORKER_PATH

    // ── Load the PDF document ────────────────────────────────────────────────
    const loadingTask = getDocument({
      data:            new Uint8Array(pdfBuffer),
      verbosity:       0,           // suppress console noise
      disableFontFace: true,        // no font loading needed for raster output
      isEvalSupported: false,       // security: no eval in worker
    })
    const pdf = await loadingTask.promise

    // ── Render page 1 ───────────────────────────────────────────────────────
    const page     = await pdf.getPage(1)
    const viewport = page.getViewport({ scale: RENDER_SCALE })
    const width    = Math.round(viewport.width)
    const height   = Math.round(viewport.height)

    // ── Draw to canvas ───────────────────────────────────────────────────────
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { createCanvas } = require('canvas') as typeof import('canvas')
    const canvas  = createCanvas(width, height)
    const ctx     = canvas.getContext('2d')

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (page.render as any)({ canvasContext: ctx, viewport }).promise

    await pdf.destroy()

    // ── Export as PNG ────────────────────────────────────────────────────────
    return canvas.toDataURL('image/png')

  } catch (err) {
    console.warn('[pdfToImage] PDF render failed:', err instanceof Error ? err.message : err)
    return null
  }
}

/**
 * Quick check: is this input likely a PDF?
 */
export function isPdfInput(input: string): boolean {
  if (input.startsWith('data:application/pdf'))   return true
  if (input.startsWith('data:application/x-pdf')) return true
  // Check raw base64 magic bytes: %PDF = 0x25 0x50 0x44 0x46 → base64 "JVBE"
  const raw = input.includes(',') ? input.split(',')[1] : input
  return raw.startsWith('JVBE')
}
